### PR TITLE
Add wired timers with kqueue support

### PR DESCRIPTION
**Pull request by gempa-jabe**
This PR introduces the timer to the reactor which sets it up with kqueue and `EVFILT_TIMER`. I have tested the implementation with epoll (Linux) and it still works as expected.

This refers to #1. @gilcel please give that a try. That is probably all I can do for you as I don't own a mac myself for compilation.

### CODE REVIEW

**Comment by gempa-jabe** [comment]
@cla-bot check

**Comment by gempa-jabe** [comment]
If that code compiles then please run `scmaster --debug`. It should not log any errors but output continuously `Timeout` every second and `******************` every 10 seconds.

**Comment by gempa-jabe** [comment]
I have installed FreeBSD and I managed to compile scmaster with this branch there. It seems to work but still has some issues with correct async handling. When connections are active it consumes a lot CPU. This has to be figured out. But at least the webpage shows up. ;)

**Comment by gempa-jabe** [comment]
I have fixed a bug in the kqueue code and now my scmaster runs happily with normal CPU on FreeBSD. It is not fully tested but at least a start.

**Comment by gilcel** [comment]
Ok I'll look at it today...thanks!

**Comment by gilcel** [comment]
I get the following error on macOS when building device.cpp.o: `error: use of undeclared identifier 's' 
I looked at it but didn't figure out directly how to fix it.

Here's the full log (sorry a bit long, since there are a lot of boost 1.60 deprecated warnings..)

```[ 24%] Building CXX object src/base/common/libs/seiscomp/CMakeFiles/seiscomp_core.dir/wired/device.cpp.o
In file included from ...src/base/common/libs/seiscomp/wired/device.cpp:23:
In file included from ...src/base/common/libs/seiscomp/core/strings.h:29:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream.hpp:21:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream_buffer.hpp:22:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/push.hpp:24:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/resolve.hpp:26:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/is_dereferenceable.hpp:12:
/usr/local/opt/boost@1.60/include/boost/type_traits/detail/bool_trait_def.hpp:18:10: warning: NOTE: Use of this header (bool_trait_def.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
         ^
In file included from ...src/base/common/libs/seiscomp/wired/device.cpp:23:
In file included from ...src/base/common/libs/seiscomp/core/strings.h:29:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream.hpp:21:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream_buffer.hpp:22:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/push.hpp:24:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/resolve.hpp:26:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/is_dereferenceable.hpp:12:
In file included from /usr/local/opt/boost@1.60/include/boost/type_traits/detail/bool_trait_def.hpp:21:
/usr/local/opt/boost@1.60/include/boost/type_traits/detail/template_arity_spec.hpp:13:10: warning: NOTE: Use of this header (template_arity_spec.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
         ^
In file included from ...src/base/common/libs/seiscomp/wired/device.cpp:23:
In file included from ...src/base/common/libs/seiscomp/core/strings.h:29:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream.hpp:21:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream_buffer.hpp:22:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/streambuf/indirect_streambuf.hpp:31:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/push.hpp:24:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/resolve.hpp:26:
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/is_dereferenceable.hpp:13:
/usr/local/opt/boost@1.60/include/boost/type_traits/detail/template_arity_spec.hpp:13:10: warning: NOTE: Use of this header (template_arity_spec.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
         ^
...src/base/common/libs/seiscomp/wired/device.cpp:478:7: error: use of undeclared identifier 's'
        if ( s->_timeout >= 0 ) applyTimeout(s);
             ^
...src/base/common/libs/seiscomp/wired/device.cpp:478:39: error: use of undeclared identifier 's'
        if ( s->_timeout >= 0 ) applyTimeout(s);
                                             ^
...src/base/common/libs/seiscomp/wired/device.cpp:1136:10: error: use of undeclared identifier 's'
                if ( !(s->_activeMode & Device::Read) ) {
                       ^
...src/base/common/libs/seiscomp/wired/device.cpp:1137:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_ADD, 0, 0, s);
                                                ^
...src/base/common/libs/seiscomp/wired/device.cpp:1137:78: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_ADD, 0, 0, s);
                                                                                                  ^
...src/base/common/libs/seiscomp/wired/device.cpp:1146:8: error: use of undeclared identifier 's'
                if ( s->_activeMode & Device::Read ) {
                     ^
...src/base/common/libs/seiscomp/wired/device.cpp:1147:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_DELETE, 0, 0, s);
                                                ^
...src/base/common/libs/seiscomp/wired/device.cpp:1147:81: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_DELETE, 0, 0, s);
                                                                                                     ^
...src/base/common/libs/seiscomp/wired/device.cpp:1168:10: error: use of undeclared identifier 's'
                if ( !(s->_activeMode & Device::Write) ) {
                       ^
...src/base/common/libs/seiscomp/wired/device.cpp:1169:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_WRITE, _defaultOps | EV_ADD, 0, 0, s);
                                                ^
...src/base/common/libs/seiscomp/wired/device.cpp:1169:79: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_WRITE, _defaultOps | EV_ADD, 0, 0, s);
                                                                                                   ^
...src/base/common/libs/seiscomp/wired/device.cpp:1178:8: error: use of undeclared identifier 's'
                if ( s->_activeMode & Device::Write ) {
                     ^
...src/base/common/libs/seiscomp/wired/device.cpp:1179:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_WRITE, _defaultOps | EV_ADD, 0, 0, s);
                                                ^
...src/base/common/libs/seiscomp/wired/device.cpp:1179:79: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_WRITE, _defaultOps | EV_ADD, 0, 0, s);
                                                                                                   ^
...src/base/common/libs/seiscomp/wired/device.cpp:1198:8: error: use of undeclared identifier 's'
                if ( s->_activeMode & Device::Read ) {
                     ^
...src/base/common/libs/seiscomp/wired/device.cpp:1199:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_DELETE, 0, 0, s);
                                                ^
...src/base/common/libs/seiscomp/wired/device.cpp:1199:81: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_DELETE, 0, 0, s);
                                                                                                     ^
...src/base/common/libs/seiscomp/wired/device.cpp:1203:8: error: use of undeclared identifier 's'
                if ( s->_activeMode & Device::Write ) {
                     ^
...src/base/common/libs/seiscomp/wired/device.cpp:1204:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_WRITE, _defaultOps | EV_DELETE, 0, 0, s);
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
make[2]: *** [src/base/common/libs/seiscomp/CMakeFiles/seiscomp_core.dir/wired/device.cpp.o] Error 1
make[1]: *** [src/base/common/libs/seiscomp/CMakeFiles/seiscomp_core.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gilcel** [comment]
I get the following error on macOS when building device.cpp.o: `error: use of undeclared identifier 's' `.

I looked at it but didn't figure out where 's' was defined.
Here's the full log (sorry a bit long, since there are a lot of boost 1.60 deprecated warnings..)

```
[ 24%] Building CXX object src/base/common/libs/seiscomp/CMakeFiles/seiscomp_core.dir/wired/device.cpp.o
In file included from ...src/base/common/libs/seiscomp/wired/device.cpp:23:
In file included from ...src/base/common/libs/seiscomp/core/strings.h:29:
....
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/detail/is_dereferenceable.hpp:12:
/usr/local/opt/boost@1.60/include/boost/type_traits/detail/bool_trait_def.hpp:18:10: warning: NOTE: Use of this header (bool_trait_def.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (bool_trait_def.hpp) is deprecated")
         ^
In file included from ...src/base/common/libs/seiscomp/wired/device.cpp:23:
In file included from ...src/base/common/libs/seiscomp/core/strings.h:29:
...
In file included from /usr/local/opt/boost@1.60/include/boost/type_traits/detail/bool_trait_def.hpp:21:
/usr/local/opt/boost@1.60/include/boost/type_traits/detail/template_arity_spec.hpp:13:10: warning: NOTE: Use of this header (template_arity_spec.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
         ^
In file included from ...src/base/common/libs/seiscomp/wired/device.cpp:23:
In file included from ...src/base/common/libs/seiscomp/core/strings.h:29:
....
In file included from /usr/local/opt/boost@1.60/include/boost/iostreams/stream.hpp:21:
/usr/local/opt/boost@1.60/include/boost/type_traits/detail/template_arity_spec.hpp:13:10: warning: NOTE: Use of this header (template_arity_spec.hpp) is deprecated [-W#pragma-messages]
# pragma message("NOTE: Use of this header (template_arity_spec.hpp) is deprecated")
         ^
...src/base/common/libs/seiscomp/wired/device.cpp:478:7: error: use of undeclared identifier 's'
        if ( s->_timeout >= 0 ) applyTimeout(s);
             ^
...src/base/common/libs/seiscomp/wired/device.cpp:478:39: error: use of undeclared identifier 's'
        if ( s->_timeout >= 0 ) applyTimeout(s);
                                             ^
...src/base/common/libs/seiscomp/wired/device.cpp:1136:10: error: use of undeclared identifier 's'
                if ( !(s->_activeMode & Device::Read) ) {
                       ^
...src/base/common/libs/seiscomp/wired/device.cpp:1137:28: error: use of undeclared identifier 's'
                        EV_SET(&ev[kevent_cnt], s->fd(), EVFILT_READ, _defaultOps | EV_ADD, 0, 0, s);
                                                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
3 warnings and 20 errors generated.
make[2]: *** [src/base/common/libs/seiscomp/CMakeFiles/seiscomp_core.dir/wired/device.cpp.o] Error 1
make[1]: *** [src/base/common/libs/seiscomp/CMakeFiles/seiscomp_core.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gilcel** [comment]
Ah yes, wrong branch...sorry...but I had to made some changes for macOS.

I can start scmaster, and I think it looks much better.
I don't get a connection to http://localhost:18180 yet but  here's the DEBUG:

```
/scmaster --debug
20:01:49 [debug] Adding plugin path: .
20:01:49 [debug] Adding plugin path: /Users/gilles/.seiscomp/plugins
20:01:49 [debug] Adding plugin path: /Users/gilles/SEISCOMP4/lib/plugins
20:01:49 [debug] Adding plugin path: /Users/gilles/SEISCOMP4/lib
20:01:49 [debug] Adding plugin path: /Users/gilles/SEISCOMP4/share/plugins
20:01:49 [debug] Adding plugin path: /Users/gilles/SEISCOMP4/share/plugins/scmaster
20:01:49 [debug] Trying to open plugin at /Users/gilles/SEISCOMP4/share/plugins/dbmysql.so
20:01:49 [info] Plugin dbmysql registered
20:01:49 [debug] Trying to open plugin at /Users/gilles/SEISCOMP4/share/plugins/scmaster/dbstore.so
20:01:49 [info] Plugin dbstore registered
20:01:49 [info] 
Plugins:
--------
 [1]
  description: MySQL database driver
       author: GFZ Potsdam <seiscomp-devel@gfz-potsdam.de>
      version: 0.9.2
          API: 14.0.0
 [2]
  description: scmaster dbstore plugin
       author: gempa GmbH <seiscomp-dev@gempa.de>
      version: 0.1.0
          API: 14.0.0

20:01:49 [info] + A 0.0.0.0/0
20:01:49 [info] + Q production
20:01:49 [info]   + G AMPLITUDE
20:01:49 [info]   + G PICK
20:01:49 [info]   + G LOCATION
20:01:49 [info]   + G MAGNITUDE
20:01:49 [info]   + G FOCMECH
20:01:49 [info]   + G EVENT
20:01:49 [info]   + G QC
20:01:49 [info]   + G PUBLICATION
20:01:49 [info]   + G GUI
20:01:49 [info]   + G INVENTORY
20:01:49 [info]   + G ROUTING
20:01:49 [info]   + G CONFIG
20:01:49 [info]   + G LOGGING
20:01:49 [info]   + G SERVICE_REQUEST
20:01:49 [info]   + G SERVICE_PROVIDE
20:01:49 [debug] Checking database 'mysql' and trying to connect with 'sysop:sysop@localhost/seiscomp'
20:01:49 [error] Connect to sysop:******@localhost:3306/seiscomp failed
20:01:49 [error] Database check... connection refused, retry
20:01:49 [error] Database check... connection not available, abort
20:01:49 [error] Failed to initialize message processor interface 'dbstore'
20:01:49 [debug] [reactor] shutdown
20:01:49 [debug] [server] shutdown
20:01:49 [debug] Shutdown sequence for queue production
20:01:49 [debug] * Shutdown worker
20:01:49 [debug] [reactor] shutdown
20:01:49 [debug] * Wait for thread
20:01:49 [debug] * Shutdown queue itself
20:01:49 [debug] [queue] Shutdown
20:01:49 [debug] [queue] Shutdown
```

**Comment by gempa-jabe** [comment]
You don't have a database plugin configured. You can simply disable the production queue in `etc/scmaster.cfg` (to be created):

```
core.plugins = "" # Remove default dbmysql
queues = withoutdatabase # That is a queue name, no command ;) 
```

Then start scmaster and try again. The idea of scmaster is to run continuously like a webserver. When it exits then it does not accepts requests and will not serve e.g. web pages.

**Comment by gempa-jabe** [comment]
But it compiles and runs! Great news!

**Comment by gilcel** [comment]
Yes it works !! (by disabling the production queue in `etc/scmaster.cfg`)
Thanks a lot!
There are some macOS specific tweaks for correctly compiling...I will try to make a pull request
or do you prefer that I put write the corrections in this thread ?

seiscomp4-scmaster-20200421

**Comment by gempa-jabe** [comment]
There is still an issue with the icons which has been fixed already but that is irrelevant in this context.
Please hold on a while until you create a PR. I am going to clean up the codes and also fix some issues with respect to BSD/OSX. Once this PR is merged, you can proceed. Please use as small PR's as possible to address a particular issue at a time otherwise I might loose orientation ;)

Thanks for testing.

**Comment by gilcel** [comment]
Ok, but you need to change line 28 in common/libs/seiscomp/wired/device.cpp from:

`#if !defined(MACOSX) && !defined(BSD)`
to:
`#if !defined(__APPLE__) && !defined(BSD)`

or else it will fail to compile.

**Comment by gempa-jabe** [comment]
Please try add the following line to device.h:

```
#include <seiscomp/core/platform/platform.h>
```

That will define MACOSX. Can you test that?

**Comment by gilcel** [comment]
Yes it works with MACOSX instead of __APPLE__, but `#include <seiscomp/core/platform/platform.h>`needs to be in device.cpp (already in device.h):
https://github.com/SeisComP/common/blob/wired-kqueue-timer/libs/seiscomp/wired/device.cpp

**Comment by gempa-jabe** [comment]
I think device.h must be moved to the top before MACOSX is being checked.

**Comment by gempa-jabe** [comment]
I have updated this branch (force pushed, so you need to reset --hard to HEAD or just cherry-pick the last commit in master). Furthermore I updated master with respect to clang compiler warnings and also removed the compiler version check if not gcc is being used. Please use this branch as basis for your adaptions.

**Comment by gempa-jabe** [comment]
> Please use this branch as basis for your adaptions.

Sorry, I will merge it and you should use master then.

**Comment by gilcel** [comment]
Ok, in `master` now...new issue:
```
src/base/common/libs/seiscomp/wired/devices/socket.cpp:65:9: error: static_cast from 'pthread_t _Nonnull' (aka '_opaque_pthread_t *') to
      'unsigned long' is not allowed
        return static_cast<unsigned long>(pthread_self());
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings and 1 error generated.
```

**Comment by gempa-jabe** [comment]
OK, will look into it.

**Comment by gilcel** [comment]
It seems to work with:
```
pthread_t SSL_thread_id_function(void) {
          return static_cast<pthread_t>(pthread_self());
}
```
but not sure if it's correct...

**Comment by gempa-jabe** [comment]
Let me check that. I am currently testing the BSD build.

**Comment by gempa-jabe** [comment]
I fixed the compilation and also linking worked with BSD.

**Comment by gempa-jabe** [comment]
Running scmaster works as well.

**Comment by gempa-jabe** [comment]
Would it be possible for me to access your build machine? Dealing here in the issue with that is a bit complicated. Please contact me vie email.

**Comment by gilcel** [comment]
Ok it works with your fix (for SSL_thread_id_function() ) but still libseiscomp_core.dylib issue...
I will look at it further (it worked with wired-kqueue-timer).
If I find time I will setup a build-machine since it's my main office machine. Will let you know.

**Comment by gempa-jabe** [comment]
If have added specialized versions of fromString() functions for all supported integer types with range checking and also added test for them. Because long and unsigned long should map to int32/uint32 or int64/uint64 both implementations should be found by the linker. Confused ...

**Comment by gempa-jabe** [comment]
> or setup a VirtualBox VM with macOS 10.14.x

If you can provide me with a VirtualBox image where the build is already prepared that would be awesome. Then I could try to fix all the issues without bothering you.

**Comment by gilcel** [comment]
No problem, you don't bother me at all...will try to setup a Virtual-Box..but will take some time.

Still same issue with linker, not related but before I had to make the following changes in `seiscomp/broker/hashset.cpp` to avoid the compiler error: 
`error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information`

```
iterator find(const void *v) const {
            #ifdef __APPLE__
		    // avoid: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
		    return iterator(_h, kh_get(int, _h, (uintptr_t)v));
		    #else
			return iterator(_h, kh_get(int, _h, (uint32_t)v));
			#endif 
		}

		void erase(iterator it) {
@@ -542,7 +547,12 @@ class KHashSetPtrBase<T, 4> {
		}

		bool contains(const void *v) const {
			return kh_get(int, _h, (uint32_t)v) != kh_end(_h);
            #ifdef __APPLE__
		        // avoid: error: cast from pointer to smaller type 'uint32_t' (aka 'unsigned int') loses information
		        return iterator(_h, kh_get(int, _h, (uintptr_t)v));
		    #else
			    return iterator(_h, kh_get(int, _h, (uint32_t)v));
			#endif   
		}
```

**Comment by gempa-jabe** [comment]
Thanks for the fix. It helped to get a more generic fix that compiles also on BSD. I pushed my latest changes but I am not sure if that helps with the linker error.

**Comment by gilcel** [comment]
Unfortunately your latest commit doesn't fix the linking error...will check later.

**Comment by gempa-jabe** [comment]
And another one in master. I reverted the last change of string conversions and tried to apply a more generic approach to available base C types. Works with Linux and BSD. Please give that one a try again.

**Comment by gilcel** [comment]
Great, your latest commit works! 
But I had to make some tweaks ```src/base/common/libs/seiscomp/gui/datamodel/originlocatorview.cpp` line 1363:
#ifdef __APPLE__
ArrivalDelegate::ArrivalDelegate(QWidget *parent)
#else
ArrivalDelegate::ArrivalDelegate(QWidget *parent = NULL)
#endif
```

**Comment by gempa-jabe** [comment]
I am glad to hear that.

What is the compile error if you don't apply the fix in originlocatorview.cpp?

**Comment by gilcel** [comment]
```
src/base/common/libs/seiscomp/gui/datamodel/originlocatorview.cpp:1364:43: error: addition of default argument on redeclaration makes this constructor a default constructor
ArrivalDelegate::ArrivalDelegate(QWidget *parent = NULL)
                                          ^        ~~~~
```

**Comment by gempa-jabe** [comment]
I will look into it. This is probably a general error and needs to be fixed anyway.

**Comment by gilcel** [comment]
Also here's the patch for `libs/seiscomp/utils/timer.h` and `libs/seiscomp/utils/timer.cpp`

```
diff --git a/libs/seiscomp/utils/timer.h b/libs/seiscomp/utils/timer.h
index 6dbeef5a9ddd6b43531199567a0a134e483fa13d..91c49a9a9cf68d0a59d9937b79162ef3f19b3779 100644
--- a/libs/seiscomp/utils/timer.h
+++ b/libs/seiscomp/utils/timer.h
@@ -28,7 +28,7 @@
 #include <boost/thread/thread.hpp>
 #include <boost/thread/mutex.hpp>
 
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 #include <list>
 #else
 #include <signal.h>
@@ -139,7 +139,7 @@ class SC_SYSTEM_CORE_API Timer {
 
 
 	private:
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 		bool deactivate(bool remove);
 
 		static void Loop();
@@ -151,7 +151,7 @@ class SC_SYSTEM_CORE_API Timer {
 #endif
 
 	private:
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 		typedef std::list<Timer*> TimerList;
 		static TimerList _timers;
 		static boost::thread *_thread;
@@ -166,7 +166,7 @@ class SC_SYSTEM_CORE_API Timer {
 		Callback         _callback;
 		boost::try_mutex _callbackMutex;
 		unsigned int     _timeout;
-#ifndef WIN32
+#if !defined(WIN32) && !defined(__APPLE__)
 		unsigned int     _timeoutNs;
 #endif
 		bool             _singleShot;
diff --git a/libs/seiscomp/utils/timer.cpp b/libs/seiscomp/utils/timer.cpp
index 433a3ae8b70a68bb4bc6fad9b25ae7c54f002d95..29a1833a901f20d293ae19940a5d4f0ad2d7ca34 100644
--- a/libs/seiscomp/utils/timer.cpp
+++ b/libs/seiscomp/utils/timer.cpp
@@ -26,7 +26,7 @@
 #include <assert.h>
 #include <iostream>
 
-#ifndef WIN32
+#if !defined(WIN32) && !defined(__APPLE__)
 #include <errno.h>
 #include <string.h>
 
@@ -98,7 +98,7 @@ Seiscomp::Core::TimeSpan StopWatch::elapsed() const {
 
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 Timer::TimerList Timer::_timers;
 boost::thread *Timer::_thread = NULL;
 boost::mutex Timer::_mutex;
@@ -111,7 +111,7 @@ boost::mutex Timer::_mutex;
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 Timer::Timer(unsigned int timeout) {
 	_singleShot = false;
-#ifndef WIN32
+#if !defined(WIN32) && !defined(__APPLE__)
 	_timerID = 0;
 #else
 	_isActive = false;
@@ -125,7 +125,7 @@ Timer::Timer(unsigned int timeout) {
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 Timer::~Timer() {
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	if ( _isActive )
 		deactivate(true);
 #else
@@ -140,8 +140,9 @@ Timer::~Timer() {
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 void Timer::setTimeout(unsigned int timeout) {
 	_timeout = timeout;
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	if ( !_timeout && _isActive )
+	    stop();
 #else
 	_timeoutNs = 0;
 	if ( !_timeout && !_timeoutNs && _timerID )
@@ -155,7 +156,7 @@ void Timer::setTimeout(unsigned int timeout) {
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 bool Timer::setTimeout2(unsigned int seconds, unsigned int nanoseconds) {
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	if ( nanoseconds )
 		return false;
 
@@ -196,14 +197,14 @@ void Timer::setSingleShot(bool s) {
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 bool Timer::start() {
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	if ( !_timeout )
 #else
 	if ( !_timeout && !_timeoutNs )
 #endif
 		return false;
 
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	boost::mutex::scoped_lock lk(_mutex);
 
 	if ( _isActive )
@@ -269,7 +270,7 @@ bool Timer::start() {
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 bool Timer::stop() {
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	return deactivate(false);
 #else
 	return destroy();
@@ -282,7 +283,7 @@ bool Timer::stop() {
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 bool Timer::disable() {
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	if ( _isActive )
 		return deactivate(true);
 	return false;
@@ -296,7 +297,7 @@ bool Timer::disable() {
 
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 bool Timer::deactivate(bool remove) {
 	assert(_isActive == true);
 
@@ -339,7 +340,7 @@ bool Timer::destroy() {
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 bool Timer::isActive() const {
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 	return _isActive;
 #else
 	return _timerID > 0;
@@ -351,7 +352,7 @@ bool Timer::isActive() const {
 
 
 // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-#ifdef WIN32
+#if defined(WIN32) || defined(__APPLE__)
 void Timer::Loop() {
 	do {
 		Core::sleep(1);
```

**Comment by gilcel** [comment]
And for `src/base/common/CMakeLists.txt`
```
IF (NOT APPLE)
    IF(GCC_VERSION VERSION_LESS "4.7")
	    MESSAGE(FATAL_ERROR "GCC version ${GCC_VERSION} found but 4.7 required as minimum")
    ENDIF(GCC_VERSION VERSION_LESS "4.7")
ENDIF (NOT APPLE)
```

**Comment by gempa-jabe** [comment]
The last patch should be in master already.

**Comment by gilcel** [comment]
Compiles fine now with all your latest commits. I will however try to clone everything from new to compile it again.

**Comment by gempa-jabe** [comment]
I am glad to hear that. Hopefully we will have much less adaptions in future to support osx.

**Comment by gilcel** [comment]
I cloned the latest repositories again...I have of course added some tweaks for macOS (to find openssl, python3 and flex-dev and boost 1.60 (since older boost-version are not available with Homebrew).
Also Unit-Testing doesn't work with boost > 1.59 ? I can of course turn Unit-Testing OFF 

```
src/base/common/libs/seiscomp/unittest/output.cpp:22:
.../seiscomp4-macOS-fresh/src/base/common/libs/seiscomp/unittest/output.h:27:10: fatal error: 'boost/test/test_observer.hpp' file not found
#include <boost/test/test_observer.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/base/common/libs/seiscomp/unittest/CMakeFiles/seiscomp_unittest.dir/output.cpp.o] Error 1
make[1]: *** [src/base/common/libs/seiscomp/unittest/CMakeFiles/seiscomp_unittest.dir/all] Error 2
make: *** [all] Error 2

real	11m6.531s
user	10m3.846s
sys	0m56.666s
```

**Comment by gempa-jabe** [comment]
We support all boost version. I have 1.72 on my machine here. For boost > 1.60 you need to include boost/test/tree/observer.hpp. But may the version check in output.h is wrong and boost 1.60 already requires this change. Can you check if the mentioned header is present in your installation?

**Comment by gilcel** [comment]
Thanks! I've just installed the latest version of boost 1.72 with Homebrew and yes `boost/test/tree/observer.hpp is available. So I will change cmake to use the latest boost version.

It compiles, but then:
```[ 65%] Building CXX object src/base/common/libs/seiscomp/test/io/recordstream/CMakeFiles/test_io_recordstream_sdsarchive.dir/sdsarchive.cpp.o
..../src/base/common/libs/seiscomp/test/io/recordstream/sdsarchive.cpp:42:2: error: reference to 'RecordStream' is ambiguous
        RecordStream::SDSArchive sds("archive");
```

Correct me if I'm wrong:
I changed all the lines with `RecordStream::SDSArchive` to `Seiscomp::RecordStream::SDSArchive` since with namespace `Seiscomp::IO::RecordStream::SDSArchive` it doesn't work.

**Comment by gempa-jabe** [comment]
That is correct. I have fixed it in master.

**Comment by gilcel** [comment]
Is "3rd-party/nll" still used in seiscomp4 ? Have some problems with INLINE defs

**Comment by gempa-jabe** [comment]
Yes, NLL is still being used in SeisComP.

Let's rest this issue in peace and open a new one.
