### ISSUE TITLE
LOCEXT: scolv hangs when xml pipe size too large

### ISSUE THREAD

**Issue by filefolder** [SeisComP/common#205]
Hi there, have noticed an issue when trying to relocate larger events using a custom plugin via `locext`. It seems that when the size of the event info XML being piped gets too large (64kb? around 200 phase picks) the child process trips the parent and `scolv` permanently hangs despite the locator working as expected.

Here is a machine synopsis if helpful, usual boulder of salt advised:

`plugins/locator/external/external.cpp`

L258 `waitpid()` precedes the L271 read loop — deadlock. The parent will not read outPipe until the child has exited, so a child whose stdout exceeds the 64 KiB pipe capacity blocks in write() while the parent blocks in waitpid(). Neither can proceed.

L249 `write(inPipe[1], content.c_str(), content.size())` — return value discarded. Two problems in one call. A blocking write interrupted by a signal after a partial transfer returns the short count rather than resuming, and scolv is a Qt process with timers and SIGCHLD in flight, so the child silently receives a truncated document. And because the write is not interleaved with reading outPipe, a child that emits output before consuming all its input deadlocks symmetrically — the parent never reaches waitpid() in that case, so it presents differently from the first defect.

L258 `waitpid()` has no EINTR retry and the flags are wrong. res <= 0 throws "system error: exec", so a waitpid() interrupted by any signal fails a location that was about to succeed, and leaves a zombie. WUNTRACED | WCONTINUED compounds it: if the child is ever stopped or continued, waitpid() returns with WIFSTOPPED/WIFCONTINUED, the WIFEXITED test at L265 fails, and the parent throws "external script exited with error" while the child is still alive and unreaped. Those flags serve no purpose here and should simply be 0. The L271 read() loop likewise treats EINTR as end-of-stream.

L166–204, the child branch, leaks scolv's file descriptors across execvp. Only fd 0 and 1 are handled; the messaging socket, the database connection, and the X11 connection are all inherited by the locator script and held for its lifetime.

**Comment by gempa-jabe** [comment]
Thanks, we will be looking into it.

**Comment by gempa-jabe** [comment]
This issue has been addressed with 6fc22aecc403156b95ef9680d10dbbe15246ed3c. Are you able to give it a try?

**Comment by filefolder** [comment]
```
[ 67%] Building CXX object src/base/common/plugins/locator/external/CMakeFiles/locext.dir/external.cpp.o
/data/seiscomp/SRC/src/base/common/plugins/locator/external/external.cpp: In member function 'virtual Seiscomp::DataModel::Origin* {anonymous}::ExternalLocator::relocate(const Seiscomp::DataModel::Origin*)':
/data/seiscomp/SRC/src/base/common/plugins/locator/external/external.cpp:214:28: error: 'RegistrationDisableGuard' is not a member of 'Seiscomp::DataModel'
  214 |                 DataModel::RegistrationDisableGuard guard;
```


I'm still on 7.2.1, does this require master?

**Comment by gempa-jabe** [comment]
Currently yes. Shall I add code here that you can just copy+paste which should work with 7.2.1?

**Comment by gempa-jabe** [comment]
```c++
/***************************************************************************
 * Copyright (C) gempa GmbH                                                *
 * All rights reserved.                                                    *
 * Contact: gempa GmbH (seiscomp-dev@gempa.de)                             *
 *                                                                         *
 * GNU Affero General Public License Usage                                 *
 * This file may be used under the terms of the GNU Affero                 *
 * Public License version 3.0 as published by the Free Software Foundation *
 * and appearing in the file LICENSE included in the packaging of this     *
 * file. Please review the following information to ensure the GNU Affero  *
 * Public License version 3.0 requirements will be met:                    *
 * https://www.gnu.org/licenses/agpl-3.0.html.                             *
 *                                                                         *
 * Other Usage                                                             *
 * Alternatively, this file may be used in accordance with the terms and   *
 * conditions contained in a signed written agreement between you and      *
 * gempa GmbH.                                                             *
 ***************************************************************************/


#define SEISCOMP_COMPONENT ExternalLocator

#include <seiscomp/logging/log.h>
#include <seiscomp/core/plugin.h>
#include <seiscomp/datamodel/eventparameters.h>
#include <seiscomp/io/archive/xmlarchive.h>
#include <seiscomp/system/environment.h>

#include "external.h"

#include <sstream>
#include <errno.h>
#include <unistd.h>
#include <sys/wait.h>


using namespace std;


namespace {
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ADD_SC_PLUGIN("Locator wrapper for external scripts", "gempa GmbH <seiscomp-devel@gempa.de>", 0, 1, 0)
REGISTER_LOCATOR(ExternalLocator, "External");
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ExternalLocator::ExternalLocator() {}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
bool ExternalLocator::init(const Config::Config &config) {
	try {
		_profiles = config.getStrings("ExternalLocator.profiles");
	}
	catch ( ... ) {}

	for ( string &p : _profiles ) {
		size_t pos = p.find(':');
		if ( pos != string::npos ) {
			_scripts[p.substr(0, pos)] = Environment::Instance()->absolutePath(p.substr(pos+1));
			p.erase(pos, string::npos);
		}
		else {
			_scripts[p] = p;
		}
	}

	return true;
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
ExternalLocator::IDList ExternalLocator::profiles() const {
	return _profiles;
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
void ExternalLocator::setProfile(const string &name) {
	_currentScript = _scripts.find(name);
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
int ExternalLocator::capabilities() const {
	return InitialLocation | DistanceCutOff | FixedDepth | IgnoreInitialLocation;
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
DataModel::Origin *ExternalLocator::locate(PickList &pickList) {
	return nullptr;
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
DataModel::Origin *ExternalLocator::locate(PickList &pickList,
                                           double initLat, double initLon,
                                           double initDepth,
                                           const Seiscomp::Core::Time &initTime) {
	return nullptr;
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
DataModel::Origin *ExternalLocator::relocate(const DataModel::Origin *origin) {
	if ( _currentScript == _scripts.end() ) {
		throw LocatorException("No profile selected");
	}

	int inPipe[2], outPipe[2];

	// Create in and out pipes
	if ( pipe(inPipe) ) {
		SEISCOMP_ERROR("Could not create stdin pipe: %s (%i)",
		               strerror(errno), errno);
		throw LocatorException("system error: stdin");
	}

	if ( pipe(outPipe) ) {
		SEISCOMP_ERROR("Could not create stdout pipe: %s (%i)",
		               strerror(errno), errno);
		close(inPipe[0]); close(inPipe[1]);
		throw LocatorException("system error: stdout");
	}

	// Call script
	pid_t pid = fork();
	if ( pid < 0 ) {
		SEISCOMP_ERROR("Could not fork sub process: %s (%i)",
		               strerror(errno), errno);
		close(inPipe[0]); close(inPipe[1]);
		close(outPipe[0]); close(outPipe[1]);
		throw LocatorException("system error: fork");
	}

	if ( pid == 0 ) {
		{
			int oldFD = inPipe[0];
			if ( dup2(oldFD, STDIN_FILENO) < 0 ) {
				_exit(200); // ERROR_CHILD_STDIN
			}
			// close redundant file descriptors
			close(inPipe[0]); close(inPipe[1]);
		}

		{
			int oldFD = outPipe[1];
			if ( dup2(oldFD, STDOUT_FILENO) < 0 ) {
				_exit(201); // ERROR_CHILD_STDOUT
			}
			// close redundant file descriptors
			close(outPipe[0]); close(outPipe[1]);
		}

		vector<string> args;
		vector<char*> cargs;
		Core::split(args, _currentScript->second.c_str(), " ");

		if ( _enableDistanceCutOff ) {
			args.push_back("--max-dist=" + Core::toString(_distanceCutOff));
		}
		if ( _ignoreInitialLocation ) {
			args.push_back("--ignore-initial-location");
		}
		if ( _usingFixedDepth ) {
			args.push_back("--fixed-depth=" + Core::toString(_fixedDepth));
		}

		for ( string &s : args ) cargs.push_back(s.data());
		cargs.push_back(nullptr);

		execvp(cargs[0], cargs.data());
		_exit(202); // ERROR_CHILD_EXEC
	}

	// Close child channels
	close(inPipe[0]);
	close(outPipe[1]);

	IO::XMLArchive ar;

	{
		// TODO: Append picks and wrap it in EventParameters
		bool wasEnabled = DataModel::PublicObject::IsRegistrationEnabled();
		DataModel::PublicObject::SetRegistrationEnabled(false);

		DataModel::EventParametersPtr ep = new DataModel::EventParameters();

		DataModel::OriginPtr copyOrg = new DataModel::Origin(*origin);

		// Copy arrivals and picks
		for ( size_t i = 0; i < origin->arrivalCount(); ++i ){
			DataModel::Arrival *arrival = origin->arrival(i);
			DataModel::Pick *pick = getPick(arrival);

			if ( !pick ) {
				throw PickNotFoundException("pick '" + arrival->pickID() + "' not found");
			}

			copyOrg->add(new DataModel::Arrival(*arrival));
			ep->add(new DataModel::Pick(*pick));
		}

		// Copy comments
		for ( size_t i = 0; i < origin->commentCount(); ++i ){
			copyOrg->add(new DataModel::Comment(*origin->comment(i)));
		}

		ep->add(copyOrg.get());

		ostringstream oss;
		ar.create(oss.rdbuf());
		ar << ep;
		ar.close();

		DataModel::PublicObject::SetRegistrationEnabled(wasEnabled);

		string content = oss.str();
		if ( write(inPipe[1], content.c_str(), content.size()) != static_cast<ssize_t>(content.size()) ) {
			close(inPipe[1]);
			close(outPipe[0]);
			throw LocatorException("could not write complete document to input of script");
		}
	}

	// Done with writing
	close(inPipe[1]);

	string content;

	char buf[512];
	int r;
	while ( (r = read(outPipe[0], buf, 512)) > 0 ) {
		content += string(buf, r);
	}

	// Close parent channel
	close(outPipe[0]);

	// Wait for script
	int status = 0;
	pid_t res = waitpid(pid, &status, WUNTRACED | WCONTINUED);
	// pid does not exist or is no child process
	if ( res <= 0 ) {
		SEISCOMP_ERROR("waitpid: %s (%i)", strerror(errno), errno);
		throw LocatorException("system error: exec");
	}

	if ( WIFEXITED(status) ) {
		int exit = WEXITSTATUS(status);
		if ( exit == EXIT_SUCCESS ) {
			istringstream iss(content);
			DataModel::Origin *tmp;
			ar.open(iss.rdbuf());
			ar >> tmp;
			ar.close();

			if ( !tmp ) {
				throw LocatorException("no origin in result document");
			}

			if ( tmp->publicID() == origin->publicID() ) {
				DataModel::PublicObject::GenerateId(tmp);
			}

			return tmp;
		}
	}

	throw LocatorException("external script exited with error");
}
// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<




// >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
}
```

**Comment by filefolder** [comment]
hah thanks for that. It compiles and the issue is solved.
